=== bherila/wpkg_packages/xsd/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.wpkg.org/config" elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.wpkg.org/config">

	<xsd:complexType name="config">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:sequence minOccurs="0" maxOccurs="1">
				<xsd:element name="languages" type="languages"></xsd:element>
			</xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="param" type="xsd:string"></xsd:element>
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="param">
		<xsd:annotation>
			<xsd:documentation>Configuration parameter entry. Defines a configuration parameter of WPKG.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence></xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>Name of the configuration parameter.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="value" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>Value to be assigned to the configuration parameter.</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="languages">
		<xsd:annotation>
			<xsd:documentation>Holds language definitions such as language-specific strings.</xsd:documentation>
		</xsd:annotation>
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="language" type="language"></xsd:element>
		</xsd:choice>
	</xsd:complexType>

	<xsd:complexType name="language">
		<xsd:annotation>
			<xsd:documentation>Language holds a concrete language specification defining message strings.</xsd:documentation>
		</xsd:annotation>
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="string" type="string"></xsd:element>
		</xsd:choice>
		<xsd:attribute name="lcid">
			<xsd:annotation>
				<xsd:documentation>
					Comma-separated list of LCID values for which this language specification is valid. For example
					specify "409,809" to match English locale. For a complete list of LCIDs see
					http://www.microsoft.com/globaldev/reference/lcid-all.mspx.
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:pattern value="[\w]+(,[\w]+)*"></xsd:pattern>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="string" mixed="true">
		<xsd:annotation>
			<xsd:documentation>Localized string definition.</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="id">
			<xsd:annotation>
				<xsd:documentation>
					Identifier for language string. Identifies the string you are going to localize.
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="notifyUserStart"></xsd:enumeration>
					<xsd:enumeration value="notifyUserStop"></xsd:enumeration>
					<xsd:enumeration value="notifyUserFail"></xsd:enumeration>
					<xsd:enumeration value="notifyUserReboot"></xsd:enumeration>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

    <xsd:element name="config" type="config">
    	<xsd:annotation>
    		<xsd:documentation>Root element of WPKG configuration.</xsd:documentation>
    	</xsd:annotation></xsd:element>
</xsd:schema>

=== bherila/wpkg_packages/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.wpkg.org/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wpkg.org/config xsd/config.xsd">
	<!--
		*******************************************************************************
		*
		* If you use wpkg_web, you can set wpkg_base to the base URL of your
		* WPKG_Web installation. NO TRAILING SLASH (/). This will allow WPKG to
		* use the web generated XML file and not require further XML Exports to the
		* file system.
		*
		* Examples:
		*     <param name='wpkg_base' value='http://wpkg.mydomain.com' />
		*     <param name='wpkg_base' value='http://www.mydomain.com/wpkg_web' />
		*     <param name='wpkg_base' value='http://USER:PASS@wpkg.mydomain.com' />
		*
		* NOTE: Replace USER and PASS with the required credentials to access your
		*       installation. Configure this user in config.php for WPKG_Web
		*       version 1.1.0 and greater.
		*
		* NOTE: If you would like to use the flat XML file instead of the web based
		*       method, leave the variable declaration as followed:
		*       <param name='wpkg_base' value='' />
		*
		* Default value      : ''
		* Command-line switch: /base:<base-url>
		******************************************************************************
	-->
	<!--
		<param name='wpkg_base' value='http://wpkg:secret@wpkg.mydomain.com' />
	-->
	<!--
		<param name='wpkg_base' value='' />
	-->


	<!--
		****************************************************************************
		* True : Do not consider wpkg.xml but check existence of packages.
		* False: Do not force re-detection. Use wpkg.xml to detect current package
		*        status
		*
		* Default value      : false
		* Command-line switch: /force
		****************************************************************************
	-->
	<!--
		<param name='force' value='false' />
	-->


	<!--
		****************************************************************************
		* True : Force installation over existing packages.
		* False: Skip package installation if package is already installed.
		*
		* Default value      : false
		* Command-line switch: /forceinstall
		****************************************************************************
	-->
	<!--
		<param name='forceInstall' value='false' />
	-->


	<!--
		****************************************************************************
		* True : Force the script to immediately quit on error.
		* False: Errors are logged but WPKG continues processing.
		*
		* Default value      : false
		* Command-line switch: /quitonerror
		****************************************************************************
	-->
	<!--
		<param name='quitonerror' value='false' />
	 -->


	<!--
		****************************************************************************
		* True : Enable debug mode. Prints lots of ugly debug messages to event log.
		* False: Disable debug logging to event log.
		*
		* NOTE: This flag is independent from the log level setting. So you can even
		*       enable debug logging to log files without setting this flag to true
		*       which prevents your event log to be flooded.
		*
		* Default value      : false
		* Command-line switch: /debug
		****************************************************************************
	-->
	<!--
		<param name='debug' value='false' />
	-->


	<!--
		****************************************************************************
		* True : Enable dryrun mode. Does not apply any changes to the system.
		*        Enables debug output and disables reboot.
		* False: Apply changes to the system.
		*
		* Default value      : false
		* Command-line switch: /dryrun
		****************************************************************************
	-->
	<!--
		<param name='dryrun' value='false' />
	-->


	<!--
		****************************************************************************
		* Should be set to true in case of unattended run (WPKG service).
		*
		* True : Disable all log messages printed to the console (cscript) or
		*        displayed as dialog boxes (wscript).
		* False: Alerts the user about ongoing activity using windows messaging.
		*
		* Default value      : false
		* Command-line switch: /quiet
		****************************************************************************
	-->
	<!--
		<param name='quiet' value='false' />
	-->


	<!--
		****************************************************************************
		* True : Disable user notification about WPKG actions using windows messaging.
		*        Should be set to true in case of unattended run (WPKG service)
		* False: Alerts the user about ongoing activity using windows messaging.
		*
		* Default value      : false
		* Command-line switch: /nonotify
		****************************************************************************
	-->
	<!--
		<param name='nonotify' value='false' />
	-->


	<!--
		****************************************************************************
		* Defines how long a user notification is displayed to the user. After
		* timeout has been reached the message will be closed. Specify 0 in order to
		* specify that messages are never closed automatically.
		* Note: This only works on Windows Vista or newer where msg.exe is
		* available.
		*
		* Default value      : 10
		* Command-line switch: -
		****************************************************************************
	-->
	<!--
		<param name='notificationDisplayTime' value='10' />
	-->


	<!--
		****************************************************************************
		* True : System does not reboot regardless of need.
		* False: Reboot the system as specified by packages.
		*
		* Default value      : false
		* Command-line switch: /noreboot
		****************************************************************************
	-->
	<!--
		<param name='noreboot' value='false' />
	-->


	<!--
		****************************************************************************
		* True : Disable export of running state to Windows registry at
		*        HKCU\Software\WPKG\running
		* False: Export running state to Windows registry at HKCU\Software\WPKG\running
		*
		* Default value      : false
		* Command-line switch: /norunningstate
		****************************************************************************
	-->
	<!--
		<param name='noRunningState' value='false' />
	-->


	<!--
		****************************************************************************
		* True : Matching of package and profile IDs is case sensitive.
		* False: Disable case sensitivity for package and profile IDs.
		*        WPKG will consider the package ID "SomePackage" and "SoMePaCkAgE"
		*        the same.
		*
		* Default value      : true
		* Command-line switch: /ignoreCase
		****************************************************************************
	-->
	<!--
		<param name='caseSensitivity' value='true' />
	-->


	<!--
		****************************************************************************
		* True : Match multiple host entries to a single host. 
		* False: Only match one host entry to the executing host. If a matching host
		*        entry is found the algorithm stops looking for further matches.
		*        This way only one profile is assigned to a host.
		*
		* Default value      : false
		* Command-line switch: /applymultiple
		****************************************************************************
	-->
	<!--
		<param name='applyMultiple' value='false' />
	-->


	<!--
		****************************************************************************
		* True : Disable all downloads. In this mode all download instructions
		*        will be simply ignored. Exactly the same way as if they were not
		*        specified in the XML at all. Use this option with caution as your
		*        install commands might require the files downloaded in download
		*        specifications.
		*        This switch/setting might be used on hosts which get the packages
		*        synchronized to the download target so the download files already
		*        exist before WPKG execution.
		* False: Default behavior. All downloads are executed as specified within
		*        the XML files.
		*
		* Default value      : false
		* Command-line switch: /noDownload
		****************************************************************************
	-->
	<!--
		<param name='noDownload' value='false' />
	-->


	<!--
		****************************************************************************
		* Use the specified command for rebooting, either with full path or relative
		* to the location of wpkg.js.
		* Setting rebootCmd to "special" will use tools\psshutdown.exe from
		* from www.sysinternals.com - if it exists
		* Any other value will make WPKG to try executing the command specified as
		* <command> and then exit with code 3010.
		*
		* Default value      : "standard"
		* Command-line switch: /rebootcmd:<command>
		****************************************************************************
	-->
	<!--
		<param name='rebootCmd' value='standard' />
	-->


	<!--
		****************************************************************************
		* Filename of the local package database (client-side) stored at
		* %SystemRoot%\system32 by default (see settings_file_path)
		*
		* Default value      : "wpkg.xml"
		* Command-line switch: -
		****************************************************************************
	-->
	<!--
		<param name='settings_file_name' value='wpkg.xml' />
	-->


	<!--
		****************************************************************************
		* Path to the local package database (client-side). It is strongly suggested
